apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voting-app
  namespace: argocd
  annotations: 
    argocd-image-updater.argoproj.io/image-list: priyaprince/voting-app:v1.x
    argocd-image-updater.argoproj.io/voting-app.update-strategy: semver
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc  
    namespace: default  
  source:
    repoURL: https://github.com/priyaprince/argocd-gitops-repo  
    targetRevision: HEAD  
    path: voting-app  
  syncPolicy:
    automated:
      prune: true  
      selfHeal: true  
      

